attributes:
  metadata:
    restrictions:
      - condition: "settings:zabbix_snmptrapd.metadata.enabled == false"
        action: disable
        message: This plugin requires SNMP trap daemon for Zabbix plugin
  hosts:
    value: ""
    label: "EMC hardware to monitor"
    description: "comma separated NAME:IP values"
    weight: 10
    type: "text"
